/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "user_roles" CASCADE;

CREATE TABLE "user_roles" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "role_id" INTEGER NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL);

